version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/" 
    schedule:
      interval: "weekly"
    pull-request-branch-name:
      # use hyphens instead of slashes to use branch name as a docker tag
      separator: "-"

  