# include the autogenerated dependencies file with the dependencies wrapped in a $wildcard() call
# this will help when some dependecy files are removed
RUST_PROFILE=${RUST_PROFILE:-release}
if [ "$RUST_PROFILE" = "release" ]; then
	CARGO_EXTRA_FLAGS="--release"
fi
rm -f $ngx_addon_dir/target/libsimple.d
cat << END                                            >> $NGX_MAKEFILE
include $ngx_addon_dir/target/libsimple.d

$ngx_addon_dir/target/libsimple.d: \$(ADDON_DEPS) $ngx_addon_dir/target/$RUST_PROFILE/libsimple.d
	sed "s#$PWD/$ngx_addon_dir/target/$RUST_PROFILE/libsimple.a:#$ngx_addon_dir/target/$RUST_PROFILE/libsimple.a: \\\$\$(wildcard#" $ngx_addon_dir/target/$RUST_PROFILE/libsimple.d > $ngx_addon_dir/target/libsimple.d
	sed -i '\$\$ s/\$\$/)/' $ngx_addon_dir/target/libsimple.d

$ngx_addon_dir/target/$RUST_PROFILE/libsimple.a $ngx_addon_dir/target/$RUST_PROFILE/libsimple.d: \$(ADDON_DEPS)
	(if test -f $HOME/.cargo/env; then . $HOME/.cargo/env; fi; cargo build --manifest-path=$ngx_addon_dir/Cargo.toml --target-dir=$ngx_addon_dir/target $CARGO_EXTRA_FLAGS)

END