[package]
name = "nginx_module"
version = "0.1.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
bindgen = "0.66.1"

[dependencies]
anyhow = "1.0.71"
bitflags = "2.3.1"
libc = "0.2.144"