name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: self-hosted-ubuntu-22-04-regular-x64

    container: rust:slim-bookworm

    steps:
    - uses: actions/checkout@v3
    - name: Build example
      run: |
        apt update
        apt install -y curl build-essential libpcre3 libpcre3-dev zlib1g zlib1g-dev libssl-dev libgd-dev libxml2 libxml2-dev uuid-dev clang
        curl http://nginx.org/download/nginx-1.25.2.tar.gz | tar xz
        cd nginx-1.25.2 && ./configure --conf-path=/etc/nginx/nginx.conf  --with-pcre  --lock-path=/var/lock/nginx.lock --pid-path=/var/run/nginx.pid --with-http_ssl_module --modules-path=/etc/nginx/modules --with-http_v2_module --add-module=../examples/simple && make && make install
    - name: Run tests
      run: cargo test --verbose
